### ISSUE TITLE
Plateform dependant tests' success

### ISSUE THREAD

**Issue by luciecastella** [IAMconsortium/nomenclature#148]
It seems that some tests (test_codelist_to_yalm and test_definition_with_custom_dimensions) do not work on Windows : the tests both check paths and the reference seems to have a different convention as the actual path on Windows. 
See images below

![image](https://user-images.githubusercontent.com/63099114/183934932-59c46190-4593-4520-88b1-e373e897e6e2.png)

![image](https://user-images.githubusercontent.com/63099114/183935101-b81ed49f-302f-4482-b9fa-f4bdd6e11673.png)

**Comment by phackstock** [comment]
Thanks for raising this @luciecastella. Looking at it quickly, I think the easiest way to fix this would be to replace the string paths used in the tests for comparison, `scenario/scenarios.yaml` and `simple_codelist/foo.yaml` with `pathlib.Path` objects and then use their string representations in the tests. 
Pathlib (https://docs.python.org/3/library/pathlib.html) is a super useful part of the standard library to display and manipulate paths in an operating system independent way. 
This is probably also a good occasion to start running our tests on multiple different operating systems. Only downside would be that this would increase our testing from currently running it three times (for python 3.8, 3.9 and 3.10) to potentially nine (for each version of python, for windows, mac os and ubuntu).
I could take care of this issue, should be fairly quick.
What do you think @danielhuppmann?

**Comment by danielhuppmann** [comment]
You're on the wrong track about the source of the error, @phackstock.

This issue is not about running the tests per se, but about a particular feature of the nomenclature package: when reading definitions from yaml files, the path of the file is added as an attribute to the dictionary-codelists, see
https://github.com/IAMconsortium/nomenclature/blob/4a57d2fcb0454de127d17bc95611453e4b2168de/nomenclature/codelist.py#L231

This obviously depends on the operating system. A simple fix would be to make the expected values in the tests independent of the OS by replacing `/` by `.` in
https://github.com/IAMconsortium/nomenclature/blob/4a57d2fcb0454de127d17bc95611453e4b2168de/tests/test_definition.py#L21
(and all other tests where this occurs).

I do not think that it is necessary to run tests on other OS on GitHub. The **nomenclature** package is still pretty basic and aimed at advanced users.

**Comment by phackstock** [comment]
Sorry for not being clear enough, I re-wrote my answer and reading it back it's not super understandable.

What I wanted to say is that I am aware of the origin of the error and my first thought was to change the exact line that you mentioned https://github.com/IAMconsortium/nomenclature/blob/4a57d2fcb0454de127d17bc95611453e4b2168de/nomenclature/codelist.py#L231
To use the `pathlib.PurePath.as_posix()` (https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix) in this place to make sure that the path gets represented in posix style regardless of the OS we're on. This would change the output that @luciecastella gets on Windows from `e_codelist\foo.yaml` to `e_codelist/foo.yaml` and therefore fix the tests.

The reason why I did not suggest it is that this might be confusing for Windows users as they would be used to normal Windows style paths with the forward slash instead of the backslash. In our error messages we report (if applicable) the yaml file where the error originated and I think it's best to have the actual OS specific path there.

I think in the end what I ended up suggesting is the same thing that you propose, making the expected values of the tests OS independent. Not sure I understand though how using `.` instead of `/` would fix the problem. I just tested it using `file = scenario.scenarios.yaml` and now the test also fails on my system. 
What should fix is using `file = Path("scenario/scenarios.yaml")` and then using `assert obs.scenario["scen_b"] == {"file": str(file)}` (with the additional `str()` around `file`) in the assert.

**Comment by danielhuppmann** [comment]
My apologies for misinterpreting your answer - I think I was projecting another problem that I ran into recently...

My idea about `.` was to use that as regex-matching so that it wouldn't matter whether its `/` or `\`...

But I think your suggestion with `as_posix()` is better. The *file* attribute is only meant to be for information (find where a variable is defined if there are multiple yaml in a project) - I cannot think of a use case whether this would be relevant in a programmatic use case. And I don't think that the confusion for Windows users is a big issue. So better to implement the simplest solution...

**Comment by phackstock** [comment]
No problem, I'll go ahead with the `as_posix()` option then.
Regarding the tests, I would say it might be useful to run a full set of Windows, Mac OS and Ubuntu as nightly tests. Then we can make sure that we don't accidentally introduce bugs for people who develop on Windows. Since we're in a public repo anyway we don't have to worry about the costs. Do you think this would be a good way to go about it?
