### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#210]
With a new release of **pyam [v1.7.0](https://github.com/IAMconsortium/pyam/releases/tag/v1.7.0)** just out including the new `require_data()` method, it's time to fix the pyam-pin and then create a new release!

One thing to think about before the release: whether to stick with the method name `CodeList.invalid_items()` (see [here](https://github.com/IAMconsortium/nomenclature/blob/72fc8a42b78572925c5b622545d69aaed746a160/nomenclature/codelist.py#L107)) or call that method `validate()` for consistency?

So `DataStructureDefinition.validate()` validates against an entire **IamDataFrame**, and
`CodeList.validate()` validates against a list of items...

What do you think @phackstock?

**Comment by phackstock** [comment]
I'm all for consistency so `CodeList.validate()` sounds like a good idea me. I'll rename it accordingly and remove the pyam version pin. 
Not sure it's really necessary to go for a full new release of nomenclature yet. The `process` function does not yet take a `RequiredDataValidator` yet. I can open a PR for that including docs and then we can create a new release.

**Comment by danielhuppmann** [comment]
Ok, sounds good, thanks!

**Comment by phackstock** [comment]
Just wanted to create two small PRs one for the pyam version and one for renaming `CodeList.invalid_items` to `CodeList.validate`. 
Turns out the second one won't work since `CodeList` inherits from `pyam.BaseModel` and that already defines a `validate` method. I could use `validate_items` instead or just keep it as is since we're not going to get it all aligned then. Alternatively we could also rename the `validate` method in `DataStructureDefinition`.

**Comment by danielhuppmann** [comment]
Good point... I guess `validate_items()` sounds better than `invalid_items()`... I would not change the DataStructureDefinition any more unless strictly necessary.

**Comment by phackstock** [comment]
Closing as release v0.8 is now live.
