### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#57]
For future releases of the nomenclature package on pypi we want a GitHub action that automatically updates the pypi entry.

Inspiration may be taken from the [`publish.yaml`](https://github.com/IAMconsortium/units/blob/main/.github/workflows/publish.yaml) workflow from the units package.

**Comment by danielhuppmann** [comment]
Because the current status of this repo is not available on pypi, I had to do a little work-around in the **openentrance** repo, first installing the requirements and then doing `pip install -e .` (because it seems to be not possible to refer to GitHub-repos in `setup.cfg`), see https://github.com/openENTRANCE/openentrance/pull/145.

This is a reminder to update the installation instructions of the **openentrance** repo once the **nomenclature** is updated on pypi.
