### ISSUE TITLE
Allow "filtering by DataStructureDefinition"

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#69]
The currently implemented `validate()` method raises an error if any row of an **IamDataFrame** is not defined in the codelist of a **DataStructureDefinition**.

There is a secondary use case where we want to filter (downselect) an **IamDataFrame** by the codelists of an **DataStructureDefinition**.

This could be done already now by the following:

```python
dsd = nomenclature.DataStructureDefinition("<path/to/definitions>")
df = pyam.IamDataFrame("<path/to/file>")
valid_df = df.filter(region=dsd.region, variable=dsd.variable)
```

This would not ensure that units are correct and all dimensions have to specified explicitly, but is probably good enough for most use cases.

Still, going forward, it might be beneficial to add a more concise way to filter. 

Best option, in my opinion:

```python
df_valid = dsd.filter(df)
```

Alternative (but might cause circular-dependency issues):

```python
df_valid = df.filter(definition=dsd)
```

**Comment by phackstock** [comment]
Very good design question, I think we should bring @meksor into this to get a third opinion. Not only about this but about our classes so far in general. 
From my point of view, I would prefer to keep it as is since I don't think that `df.filter(region=dsd.region, variable=dsd.variable)` is particularly ugly. It clearly shows the user what's going on and does not add any dependencies on either side.
I you would like to have a shorthand I would actually prefer adding it on the pyam side like `df.filter_dsd()` or something along those lines. Reason being that it serves the same functionality as `df.filter` and so it should live on the same side.

**Comment by meksor** [comment]
I agree with Philip entirely!

**Comment by phackstock** [comment]
Can we close this @danielhuppmann?
